### ISSUE TITLE
Does Chump support sending image attachments or is this planned?

### ISSUE THREAD

**Issue by klover1** [karanlyons/chump#19]
Great library- I've been using it in one of my projects. 

Do you plan to add in sending images/attachments as was introduced in January by Pushover ?

**Comment by karanlyons** [comment]
I’d like to at some point, but currently haven’t been able to find the time. I’m not using Pushover in any of my day to day work so it’s hard to justify the cost in terms of time/money. If someone would like to open a PR that adds this feature within the same level of quality (checking for potential errors before submitting any API calls, not relying on external dependencies, supporting Py(Py)2/3, etc.) I’d be happy to accept it.

**Comment by klovanone** [comment]
Thanks for the reply. I had a look at the source code and you are correct it would be quite a bit of work to implement with all the checks, and like you I don't have enough time at the moment! 

I ended up using requests library  as a quick workaround to send images in the meantime.  THanks again !

**Comment by karanlyons** [comment]
No problem! Sorry the library isn’t more fully featured at the moment, and thank you for understanding the difficulties of OSS :)
