### ISSUE TITLE
IndexError while trying to raise ValueError when application token is bad

### ISSUE THREAD

**Issue by thp** [karanlyons/chump#8]
Forwarding from https://github.com/thp/urlwatch/issues/102:

```
  File "/Users/ervsts/Library/Python/3.5/lib/python/site-packages/chump/__init__.py", line 209, in __setattr__
    raise ValueError('Bad application token: expected string matching [a-zA-Z0-9]{30}, got {!r}'.format(value))
IndexError: tuple index out of range
```

The `.format()` method here interprets `{}` as fields for formatting and fails, since only one parameter is provided, you probably need to change this to:

```
raise ValueError('Bad application token: expected string matching {}, got {!r}'.format('[a-zA-Z0-9]{30}', value))
```

**Comment by karanlyons** [comment]
Well that’s embarrassing. Take a look at the latest commits and let me know if they solve the problem, lest I embarrass myself further.

**Comment by thp** [comment]
Should be good now, thanks :)

**Comment by karanlyons** [comment]
It’s up on PyPI now. Thanks for the report!
