### ISSUE TITLE
Tag releases in git

### ISSUE THREAD

**Issue by sbraz** [karanlyons/chump#9]
Hi, it would be nice if you could tag all releases in git, it makes it easier to see what changed from 1.5.1 to 1.5.2 for instance. Do you think that's possible?
I don't really care about old releases but it would be nice if the 1.5.x ones could be tagged.

**Comment by karanlyons** [comment]
Done from [1.0.0](https://github.com/karanlyons/chump/tree/1.0.0) (first PyPI release) onward.
